all: lab02-1 lab02-2

lab02-1: Jordan_Nicholas_Lab02-1.c
	gcc Jordan_Nicholas_Lab02-1.c -o lab02-1

lab02-2: Jordan_Nicholas_Lab02-2.c
	gcc Jordan_Nicholas_Lab02-2.c -o lab02-2

clean:
	rm -f lab02-1
	rm -f lab02-2
	rm -f *.o
